---
- name: APT Upgrade
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: APT Upgrade
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: true
